version: '3'

services:

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./frontend:/app
      - ./certs/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - ./certs/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - backend
    environment:
      - VITE_NAME=FelixIvander

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
      - "80:80"
    volumes:
      - ./backend/db:/app/db
      - ./certs:/etc/ssl/certs
      - ./certs:/etc/ssl/private
    environment:
      - NAME=FelixIvander
